GET http://localhost:3000/authors

###

GET http://localhost:3000/authors/64ada086abb4a998eca7938b

###

POST http://localhost:3000/authors
Content-Type: application/json

{
    "firstName": "Giada",	
    "lastName": "Pes",
    "email": "giada.pes@hotmail.com",
    "birthDate": "2001-02-21",
    "avatar": "https://www.example.com"
}

###

DELETE http://localhost:3000/authors/64b592bb5d5bd4311f3ea96b

###

PATCH http://localhost:3000/authors/64ada086abb4a998eca7938b
Content-Type: application/json

{
    "firstName": "Alessio"
}

###

PUT http://localhost:3000/authors/64ada086abb4a998eca7938b
Content-Type: application/json

{
    "firstName": "Alessio new",
    "lastName": "Pes new"
}