GET http://localhost:3000/authors

###

GET http://localhost:3000/authors/64ada086abb4a998eca7938b

###

POST http://localhost:3000/authors
Content-Type: application/json

{
    "firstName": "Alessio",	
    "lastName": "Pes",
    "email": "alessio.pes@hotmail.com",
    "birthDate": "1997-12-22",
    "avatar": "https://www.example.com"
}

###

DELETE http://localhost:3000/authors/64ad8414db86c0906460dc55

###

PATCH http://localhost:3000/authors/64ada086abb4a998eca7938b
Content-Type: application/json

{
    "firstName": "Alessio"
}

###

PUT http://localhost:3000/authors/64ada086abb4a998eca7938b
Content-Type: application/json

{
    "firstName": "Alessio new",
    "lastName": "Pes new"
}