GET http://localhost:3000/blogPosts

###

GET http://localhost:3000/blogPosts/64bd07a2c0ea38210389ee35

###

POST http://localhost:3000/blogPosts
Content-Type: application/json

{
  "category": "Beauty",
  "title": "Titolo Post 2",
  "cover": "https://example.com/test.jpg",
  "readTime": {
    "value": 5,
    "unit": "minuti"
  },
  "author": "64bcffa1573536557cdc68cf",
  "content": "<p>Contenuto del post</p>"
}

###

PUT http://localhost:3000/blogPosts/64b58da91154745f4ab7a294
Content-Type: application/json

{
  "title": "Titolo modificato",
  "content": "<p>Contenuto modificato</p>"
}

###

DELETE http://localhost:3000/blogPosts/64bd00ac605d5ecbb5f7061c

###

// DELETE /blogPosts => Elimina tutti i post
DELETE http://localhost:3000/blogPosts

###

GET http://localhost:3000/blogPosts?title=alessio
