GET http://localhost:5050/database

###

GET http://localhost:5050/database/64ad8400326f76976304148c

###

POST http://localhost:5050/database
Content-Type: application/json

{
    "firstName": "Alessio",	
    "lastName": "Pes",
    "email": "alessio.pes@hotmail.com",
    "birthDate": "1997-12-22",
    "avatar": "https://www.example.com"
}

###

DELETE http://localhost:5050/database/64ad8414db86c0906460dc55

###

PATCH http://localhost:5050/database/64ada086abb4a998eca7938b
Content-Type: application/json

{
    "firstName": "Alessio"
}